version: '3'
services:
  docker-nacos:
    image: nacos/nacos-server:v2.2.3
    restart: always
    container_name: 'dev_nacos'
    volumes:
      - "./nacos/logs:/home/nacos/logs"
      - "./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties"
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
    ports:
      - "8848:8848"
    networks:
      - dev_net
  postgres:
    image: 'postgres:15'
    restart: always
    container_name: 'dev_postgres'
    environment:
      POSTGRES_PASSWORD: lizhijun
    volumes:
      - ./postgres/data:/var/lib/postgresql/pgdata
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - default
      - dev_net
  etcd:
    image: 'bitnami/etcd:3.5.5'
    restart: always
    container_name: 'dev_etcd'
    volumes:
      - "./etcd/data:/bitnami/etcd/data"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    expose:
      - 2379
      - 2380
    networks:
      - default
      - dev_net
  mysql:
    image: 'mysql:8.0.23'
    restart: always
    container_name: 'dev_mysql'
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/conf:/etc/mysql/conf.d
        - ./mysql/logs:/logs
    environment:
        - MYSQL_ROOT_HOST=%
        - MYSQL_ROOT_PASSWORD=lizhijun
        - MYSQL_USER=dba
        - MYSQL_PASSWORD=lizhijun
    command:
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
    ports:
        - 3306:3306
    expose:
      - 3306
    networks:
      - default
      - dev_net
  redis:
    image: 'redis:5.0.13'
    restart: always
    container_name: 'dev_redis'
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - default
      - dev_net
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    # command: ['redis-server', '--requirepass', 'lizhijun']

networks:
  dev_net:
    external: true