version: '3'
services:
  redis:
    image: 'redis:6.0'
    restart: always
    container_name: 'rol_dev_redis'
    ports:
        - 6379:6379
    volumes:
      - ./data:/data
    command: ['redis-server', '--requirepass', 'rol2021']